[[main]]
  identifier = "documentation"
  name = "Documentation"
  url = "https://netket.readthedocs.io/en/latest/index.html"
  weight = 80
  
[[main]]
  identifier = "api"
  name = "API Reference"
  url = "https://netket.readthedocs.io/en/latest/api/api.html"
  weight = 1000

[[links]]
  identifier = 'github'
  pre = "<i class='bi bi-github'></i>"
  url = "http://www.github.com/netket/netket"
  weight = 90

[[links]]
  identifier = 'twitter'
  pre = "<i class='bi bi-twitter'></i>"
  url = "https://twitter.com/netketorg"
  weight = 90

[[links]]
  identifier = 'slack'
  pre = "<i class='bi bi-slack'></i>"
  url = "https://join.slack.com/t/mlquantum/shared_invite/zt-11x4qfoc0-hTge76XqJApq_6vUFmaiYw"
  weight = 100
